# reload config with prefix-r:
bind r source-file ~/.config/tmux/tmux.conf \; display "reloaded config"

# open tmux in current path:
bind c new-window -c "#{pane_current_path}"

# True color settings
set -g default-terminal "$TERM"
set -ag terminal-overrides ",$TERM:Tc"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# List of plugins
set -g @plugin 'rose-pine/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin "janoamaral/tokyo-night-tmux"
# set -g @tokyo-night-tmux_window_id_style digital
# set -g @tokyo-night-tmux_pane_id_style hsquare
# set -g @tokyo-night-tmux_zoom_id_style dsquare
set -g @rose_pine_variant 'midnight' # Options are 'main', 'moon' or 'dawn'
# To update plugin for future revisions or bug fixes, do the "Prefix + U" keycombo
set-option -g status-position top

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'


# tmux vim navigator
# set -g @plugin 'christoomey/vim-tmux-navigator'
# run '~/.config/tmux/plugins/tpm/tpm'

# dont scroll through history
set -g history-limit 5000
set -g mouse on
unbind -n MouseDrag1Pane

# leader-r to reload config:
# unbind r
# bind r source-file ~/.config/tmux/tmux.conf

# dont p
set -sg escape-time 0

# set -g prefix M-Space
# unbind C-b

# bind-key -n S-C-h select-pane -L
# bind-key -n S-C-j select-pane -D
# bind-key -n S-C-k select-pane -U
# bind-key -n S-C-l select-pane -R
# bind-key -n M-h select-pane -L
# bind-key -n M-j select-pane -D
# bind-key -n M-k select-pane -U
# bind-key -n M-l select-pane -R
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind Enter split-window -h
# bind-key -n M-Enter split-window -h
# bind-key -n C-S-Enter split-window -h
# bind-key -n M-S-Enter split-window -h

bind-key -n M-L move-window -r
bind-key -n M-H move-window

# set-option -g status-style bg=blue
# set-option -g status-style fg=white
# set-option -g status-style fg=blue

bind-key -n M-v split-window -h
bind-key -n M-s split-window -v

bind-key -n M-x kill-pane

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
